AWSTemplateFormatVersion: 2010-09-09

#   --------------------------------------------------------
#   Version History
#
#   v1.0.0    J. Silva   Initial Version
#   --------------------------------------------------------

Description: >-
    Creates S3 bucket for LogShipper Lambda functions 

Resources:

  #   -------------------
  #   Code Repo Bucket
  #   -------------------

  LambdaArtefactsBucket:
      Type: AWS::S3::Bucket
      Properties:
          BucketEncryption: 
            ServerSideEncryptionConfiguration: 
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
          BucketName:
              Fn::Join:
              - ""
              - - "lambda-artefacts-"
                - Ref: AWS::AccountId
          OwnershipControls:
            Rules:
            - ObjectOwnership: BucketOwnerEnforced
  
  LambdaArtefactBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
          Bucket: 
              Ref: LambdaArtefactsBucket
          PolicyDocument:
              Statement:
                -
                  Sid: "CloudformationPermissions1"
                  Effect: "Allow"
                  Principal:
                    Service:
                    - "cloudformation.amazonaws.com"
                  Action:
                  - "s3:GetBucketAcl"
                  - "s3:ListBucket"
                  Resource: !GetAtt LambdaArtefactsBucket.Arn

                -
                  Sid: "CloudformationPermissions2"
                  Effect: "Allow"
                  Principal:
                    Service:
                    - "cloudformation.amazonaws.com"
                  Action:
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                  Resource:
                    Fn::Join:
                      - ""
                      -
                        - !GetAtt LambdaArtefactsBucket.Arn
                        - "/*"
                -
                  Sid: "LambdaBucketSSL"
                  Action: s3:*
                  Principal: "*"
                  Effect: Deny
                  Resource:
                    - Fn::Join:
                      - ""
                      -
                        - !GetAtt LambdaArtefactsBucket.Arn
                    - Fn::Join:
                      - ""
                      -
                        - !GetAtt LambdaArtefactsBucket.Arn
                        - "/*"
                  Condition:
                    Bool:
                      "aws:SecureTransport": "false"
                -
                  Sid: "AWSAccessArtefactsBucketSSL"
                  Action: "s3:*"
                  Effect: Deny
                  Principal: "*"
                  Resource:
                    - Fn::Join:
                      - ""
                      -
                        - !GetAtt LambdaArtefactsBucket.Arn
                    - Fn::Join:
                      - ""
                      -
                        - !GetAtt LambdaArtefactsBucket.Arn
                        - "/*"
                  Condition:
                    Bool:
                      "aws:SecureTransport": "false"
                
      