AWSTemplateFormatVersion: 2010-09-09

#   --------------------------------------------------------
#   Version History
#
#   v1.0  J. Vandenbergen   Initial Version
#   --------------------------------------------------------

Description: >-
  v1.0. Script to create SecurityHub in SecLog master accountS

Resources:
  rSecHubWithTags:
    Type: "AWS::SecurityHub::Hub"
    Properties:
      Tags:
        "Project" : "secLZ"

Outputs:
  HubArn:
    Value: !Ref rSecHubWithTags