AWSTemplateFormatVersion: 2010-09-09

#   --------------------------------------------------------
#   Version History
#
#   v1.0.0  J. Vandenbergen   Initial Version
#   v1.1.0  J. Silva          Enables optional resource installation (SOC integration)
#   --------------------------------------------------------

Description: >-
  v1.0. Script to create Guardduty detector

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Guardduty"
        Parameters:
          - GuardDutyMasterId

Parameters:
  LogsRetentionInDays:
    Description: 'Specifies the number of days you want to retain CloudTrail log events in the CloudWatch Logs.'
    Type: Number
    Default: 90
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  AwsConfigLogsGroupName:
    Type: String
    Default: /aws/events/config
    Description: CloudWatch LogGroup name for AWS config cloudwatch events
  SNSNotificationTopic:
    Type: String
    Default: ""
    Description: "Local Admin SNS Topic for Landing Zone"
  SecLogMasterAccountId:
    Type: String
    Default: ""
    Description: "Contains account id of SecLogMaster"
  SecLogMasterAccountRegion:
    Type: String
    Default: "eu-west-1"
    Description: "Contains account region of SecLogMaster"
  EnableSecLogIntegrationFoGuardDutyParam:
    Type: String
    Description: "Enable SecLog integration for GuardDuty?"
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'

Conditions:

  IsSecLogMasterAccountWithSOCIntegration: !And
  - !Equals
    - !Ref EnableSecLogIntegrationFoGuardDutyParam
    - 'true'

Resources:
 
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
        Enable: true
        FindingPublishingFrequency: FIFTEEN_MINUTES



  # GuardDuty CloudWatch Event - For GuardDuty
  GuardDutyEvents: 
    Type: AWS::Events::Rule
    DependsOn: AwsConfigLogGroup
    Condition: IsSecLogMasterAccountWithSOCIntegration
    Properties: 
      Name: SECLZ-GuardDuty-Event
      Description: "GuardDuty Event Handler"
      EventPattern: 
        source:
        - aws.guardduty
      State: ENABLED
      Targets:
        - 
          Arn: !Ref SNSNotificationTopic
          Id: "GuardDutySNSTopic-SecLog"
        -
          Arn: !Sub "arn:aws:logs:${SecLogMasterAccountRegion}:${SecLogMasterAccountId}:log-group:${AwsConfigLogsGroupName}:*"
          Id: "AwsConfigCloudWatch-Seclog"
  