AWSTemplateFormatVersion: 2010-09-09

#   --------------------------------------------------------
#   Version History
#
#   v1.0.0  J. Vandenbergen   Initial Version
#   v1.1.0  J. Silva          Enables optional resource installation (SOC integration)
#   --------------------------------------------------------

Description: >-
  v1.0. Script to create Guardduty detector

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Guardduty"
        Parameters:
          - GuardDutyMasterId

Parameters:
  SNSNotificationTopic:
    Type: String
    Default: 
    Description: "Local Admin SNS Topic for Landing Zone"

Resources:
 
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
        Enable: true
        FindingPublishingFrequency: FIFTEEN_MINUTES

  GuardDutyEvents: 
    Type: AWS::Events::Rule
    DependsOn: AwsConfigLogGroup
    Condition: IsSecLogMasterAccount
    Properties: 
      Name: SECLZ-GuardDuty-Event
      Description: "GuardDuty Event Handler"
      EventPattern: 
        source:
        - aws.guardduty
      State: ENABLED
      Targets:
        - 
          Arn: !Ref SNSNotificationTopic
          Id: "GuardDutySNSTopic-SecLog"
        -
          Arn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${AwsConfigLogGroup}"
          Id: "AwsConfigCloudWatch-Seclog"