AWSTemplateFormatVersion: 2010-09-09

#   --------------------------------------------------------
#   Version History
#
#   v1.0  J. Vandenbergen   Initial Version
#   --------------------------------------------------------

Description: >-
  v1.0. Script to create Guardduty detector

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Guardduty"
        Parameters:
          - GuardDutyMasterId

Parameters:
  LogsRetentionInDays:
    Description: 'Specifies the number of days you want to retain CloudTrail log events in the CloudWatch Logs.'
    Type: Number
    Default: 90
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  AwsConfigLogsGroupName:
    Type: String
    Default: /aws/events/config
    Description: CloudWatch LogGroup name for AWS config cloudwatch events
  FirehoseDestinationArn:
    Type: String
    Default: ""
    Description: The ARN of the firehose stream aggregating the logs in the DIGIT C2 Log Aggregation Central Account
  SNSNotificationTopic:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /org/member/SecLog_sns_arn
    Description: "Local Admin SNS Topic for Landing Zone"
  SecLogMasterAccountId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /org/member/SecLogMasterAccountId
    Description: "Contains account id of SecLogMaster"
  EnableSecLogIntegrationFoGuardDutyParam:
    Type: String
    Description: "Enable SecLog integration for GuardDuty?"
    Default: true
    AllowedValues:
    - true
    - false

Conditions:
  IsSecLogMasterAccount: !Equals
    - !Ref AWS::AccountId
    - !Ref SecLogMasterAccountId

  IsSecLogMasterAccountWithoutSOCIntegration: !And
  - !Equals
    - !Ref AWS::AccountId
    - !Ref SecLogMasterAccountId
  - !Equals
    - !Ref EnableSecLogIntegrationFoGuardDutyParam
    - 'false'

  IsSecLogMasterAccountWithSOCIntegration: !And
  - !Equals
    - !Ref AWS::AccountId
    - !Ref SecLogMasterAccountId
  - !Equals
    - !Ref EnableSecLogIntegrationFoGuardDutyParam
    - 'true'

Resources:
  AwsConfigLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: IsSecLogMasterAccount
    Properties:
      LogGroupName: !Ref AwsConfigLogsGroupName
      RetentionInDays: !Ref LogsRetentionInDays

  AwsConfigSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Condition: IsSecLogMasterAccountWithSOCIntegration
    Properties:
      DestinationArn: !Ref 'FirehoseDestinationArn'
      FilterPattern: ''
      LogGroupName: !Ref 'AwsConfigLogGroup'

  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
        Enable: true
        FindingPublishingFrequency: FIFTEEN_MINUTES

  CloudWatchEventsLogGroupRole:
    Type: AWS::IAM::Role
    Condition: IsSecLogMasterAccountWithSOCIntegration
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: SECLZ-CloudWatchEvents-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: logs:CreateLogStream
              Resource:
              - !GetAtt AwsConfigLogGroup.Arn
            - Effect: Allow
              Action: logs:PutLogEvents
              Resource:
              - !GetAtt AwsConfigLogGroup.Arn

  # GuardDuty CloudWatch Event - For GuardDuty
  GuardDutyEvent: 
    Type: AWS::Events::Rule
    Condition: IsSecLogMasterAccountWithSOCIntegration
    Properties: 
      Name: SECLZ-GuardDuty-Event
      Description: "GuardDuty Event Handler"
      EventPattern: 
        source:
        - aws.guardduty
      State: ENABLED
      Targets:
        - 
          Arn: !Ref SNSNotificationTopic
          Id: "GuardDutySNSTopic-SecLog"
        -
          Arn: !GetAtt AwsConfigLogGroup.Arn
          Id: "AwsConfigCloudWatch-Seclog"
  
  GuardDutyEvent: 
    Type: AWS::Events::Rule
    Condition: IsSecLogMasterAccountWithoutSOCIntegration
    Properties: 
      Name: SECLZ-GuardDuty-Event
      Description: "GuardDuty Event Handler"
      EventPattern: 
        source:
        - aws.guardduty
      State: ENABLED
      Targets:
        - 
          Arn: !Ref SNSNotificationTopic
          Id: "GuardDutySNSTopic-SecLog"