AWSTemplateFormatVersion: 2010-09-09

#   --------------------------------------------------------
#   Version History
#
#   v1.0.0  J. Vandenbergen   Initial Version
#   v1.1.0  J. Silva          Enables optional resource installation (SOC integration)
#   --------------------------------------------------------

Description: >-
  v1.0. Script to create Guardduty detector

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Guardduty"
        Parameters:
          - GuardDutyMasterId

Parameters:
  SecLogMasterAccountId:
    Type: String
    Description: "ID of thee Landing Zone Account"

Resources:

  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
        Enable: true
        FindingPublishingFrequency: FIFTEEN_MINUTES


  # Enable notifications for AWS GuardDuty Rule compliance changes in client account to event bus
  GuardDutyRuleComplianceChangeEvent:
    Type: AWS::Events::Rule
    Condition: IsNotSecLogMasterAccount
    DependsOn: AWSEventsInvokeEventBusSecLogRole
    Properties:
      Name: SECLZ-GuardDuty-Events-CloudWatch-Rule-To-SecLog
      Description: 'Landing Zone rule to send notification on GuardDuty Events to SecLog eventbus.'
      RoleArn: 
        Fn::GetAtt: 
        - "AWSEventsInvokeEventBusSecLogRole"
        - "Arn"
      EventPattern:
        {
          "source": [
            "aws.guardduty"
          ]
        }
      State: ENABLED
      Targets:
      - Id: "CrossAccountTargetId"
        Arn: !Sub "arn:aws:events:${AWS::Region}:${SecLogMasterAccountId}:event-bus/default"

  CloudWatchEventsLogGroupRole:
    Type: AWS::IAM::Role
    Condition: IsSecLogMasterAccount
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: SECLZ-CloudWatchEvents-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: logs:CreateLogStream
              Resource:
              - !GetAtt GuardDutyLogGroup.Arn
            - Effect: Allow
              Action: logs:PutLogEvents
              Resource:
              - !GetAtt GuardDutyLogGroup.Arn
            

  # GuardDuty CloudWatch Event - For GuardDuty
  GuardDutyEvents: 
    Type: AWS::Events::Rule
    DependsOn: GuardDutyLogGroup
    Condition: IsSecLogMasterAccount
    Properties: 
      Name: SECLZ-GuardDuty-Event
      Description: "GuardDuty Event Handler"
      EventPattern: 
        source:
        - aws.guardduty
      State: ENABLED
      Targets:
        - 
          Arn: !Ref SNSNotificationTopic
          Id: "GuardDutySNSTopic-SecLog"
        -
          Arn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${GuardDutyLogGroup}"
          Id: "AwsGuardDutyCloudWatch-Seclog"
 