AWSTemplateFormatVersion: 2010-09-09

#   --------------------------------------------------------
#   Version History
#
#   v1.0.0    J. Silva   Initial Version
#   --------------------------------------------------------

Description: >-
    Creates S3 bucket for LogShipper Lambda functions 
Parameters:  
  CloudtrailKMSarn:
    Type: AWS::SSM::Parameter::Value<String>
    Description: arn for KMS key to encrypt cloudtrail
    Default: "/org/member/KMSCloudtrailKey_arn"

Resources:

  #   -------------------
  #   Code Repo Bucket
  #   -------------------

  LambdaArtefactsBucket:
      Type: AWS::S3::Bucket
      Properties:
          BucketName:
              Fn::Join:
              - ""
              - - "lambda-artefacts-"
                - Ref: AWS::AccountId
          BucketEncryption:
              ServerSideEncryptionConfiguration: 
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: aws:kms
                  KMSMasterKeyID: !Ref CloudtrailKMSarn 
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
  
  LambdaArtefactBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
          Bucket:
              Ref: LambdaArtefactsBucket
          PolicyDocument:
              Statement:
                -
                  Sid: "CloudformationPermissions1"
                  Effect: "Allow"
                  Principal:
                    Service:
                    - "cloudformation.amazonaws.com"
                  Action:
                  - "s3:GetBucketAcl"
                  - "s3:ListBucket"
                  Resource: !GetAtt LambdaArtefactsBucket.Arn

                -
                  Sid: "CloudformationPermissions2"
                  Effect: "Allow"
                  Principal:
                    Service:
                    - "cloudformation.amazonaws.com"
                  Action:
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  Resource:
                    Fn::Join:
                      - ""
                      -
                        - !GetAtt LambdaArtefactsBucket.Arn
                        - "/*"
                
      