AWSTemplateFormatVersion: 2010-09-09

#   --------------------------------------------------------
#   Version History
#
#   v1.0.0  J. Vandenbergen   Initial Version
#   v1.1.0  J. Silva          Enables optional resource installation (SOC integration)
#   --------------------------------------------------------

Description: >-
  v1.0. Script to create Guardduty detector

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Guardduty"
        Parameters:
          - GuardDutyMasterId

Parameters:
  SecLogMasterAccountRegion:
    Type: String
    Description: "Region of the Landing Zone Account"
  SecLogMasterAccountId:
    Type: String
    Description: "ID of thee Landing Zone Account"

Resources:
 
  AWSEventsInvokeEventBusSecLogRole:
    Type: AWS::IAM::Role
    Properties: 
      Description: "Service Linked role to send messages to event bus of seclog account"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AWSEventsInvokeEventBusSecLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "events:PutEvents"
                Resource: !Join 
                  - ''
                  - - 'arn:aws:events:'
                    - !Sub "${SecLogMasterAccountRegion}:${SecLogMasterAccountId}:"
                    - 'event-bus/default'

  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
        Enable: true
        FindingPublishingFrequency: FIFTEEN_MINUTES

  # Enable notifications for AWS Config Rule compliance changes in client account to event bus
  ConfigRuleComplianceChangeEvent:
    Type: AWS::Events::Rule
    DependsOn: AWSEventsInvokeEventBusSecLogRole
    Properties:
      Name: SECLZ-GuardDuty-Events-CloudWatch-Rule-To-SecLog
      Description: 'Landing Zone rule to send notification on GuardDuty Events to SecLog eventbus.'
      RoleArn: 
        Fn::GetAtt: 
        - "AWSEventsInvokeEventBusSecLogRole"
        - "Arn"
      EventPattern:
        {
          "source": [
            "aws.guardduty"
          ]
        }
      State: ENABLED
      Targets:
      - Id: "CrossAccountTargetId"
        Arn: !Sub "arn:aws:events:${SecLogMasterAccountRegion}:${SecLogMasterAccountId}:event-bus/default"