AWSTemplateFormatVersion : "2010-09-09"

#   --------------------------------------------------------
#   Version History
#
#   v1.0  J. Vandenbergen   Initial Version
#   --------------------------------------------------------

Description: >-
  v1.0. Script to create local SNS-Topic in client accounts for security notifications. Will forward to central SNS-topics

Parameters:
  LocalNotifyDisplayName:
    Type: 'String'
    Default: EC-LZ-Local-Notify
    Description: SNS display name for security administrator(s)
  LocalNotificationTopicName:
    Type: 'String'
    Default: EC-Landing-Zone-Local-Security-Notification
    Description: Account Local SNS topic name for security notification
  SNSNotificationTopic:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /org/member/SecLog_sns_arn
    Description: "Local Admin SNS Topic for Landing Zone"
  LogsRetentionInDays:
    Description: 'Specifies the number of days you want to retain notification forwarding log events in the Lambda log group.'
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

Resources:
  LocalSNSNotificationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: !Ref LocalNotifyDisplayName
      TopicName: !Ref LocalNotificationTopicName

  LocalSNSNotificationPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      Topics:
        - !Ref LocalSNSNotificationTopic
      PolicyDocument:
        Id: LocalSNSNotificationTopicPolicy
        Version: 2012-10-17
        Statement:
          - Sid: __default_statement_ID
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
            - SNS:GetTopicAttributes
            - SNS:SetTopicAttributes
            - SNS:AddPermission
            - SNS:RemovePermission
            - SNS:DeleteTopic
            - SNS:Subscribe
            - SNS:ListSubscriptionsByTopic
            - SNS:Publish
            - SNS:Receive
            Resource: !Ref LocalSNSNotificationTopic
            Condition:
              StringEquals:
                AWS:SourceOwner: !Sub ${AWS::AccountId}
          - Sid: TrustCWEToPublishEventsToMyTopic
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: SNS:Publish
            Resource: !Ref LocalSNSNotificationTopic

  SNSNotificationSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: !GetAtt ForwardSnsNotification.Arn
      Protocol: lambda
      TopicArn: !Ref LocalSNSNotificationTopic

  SNSInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref LocalSNSNotificationTopic
      FunctionName: !GetAtt ForwardSnsNotification.Arn

  ForwardSnsNotificationLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'lambda.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
      - PolicyName: sns
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - 'sns:publish'
            Resource: !Join
                - ':'
                - - 'arn:aws'
                  - !Select [2, !Split [":", !Ref SNSNotificationTopic]]
                  - !Sub ${AWS::Region}
                  - !Select [4, !Split [":", !Ref SNSNotificationTopic]]
                  - !Select [5, !Split [":", !Ref SNSNotificationTopic]]
  ForwardSnsNotification:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: LandingZoneLocalSNSNotificationForwarder
      Description: AWS Landing Zone SNS message forwarding function for aggregating account notifications.
      Code:
        ZipFile:
          !Sub |
            from __future__ import print_function
            import boto3
            import json
            import os
            def lambda_handler(event, context):
                #print("Received event: " + json.dumps(event, indent=2))
                sns = boto3.client('sns')
                subject=event['Records'][0]['Sns']['Subject']
                if subject is None:
                    subject = 'None'
                message = event['Records'][0]['Sns']['Message']
                try:
                    msg = json.loads(message)
                    message = json.dumps(msg, indent=4)
                    if 'detail-type' in msg:
                      subject = msg['detail-type']
                except:
                    print('Not json')
                response = sns.publish(
                    TopicArn=os.environ.get('sns_arn'),
                    Subject=subject,
                    Message=message
                )
                print(response)
                return response
      Handler: 'index.lambda_handler'
      MemorySize: 128
      Role: !GetAtt 'ForwardSnsNotificationLambdaRole.Arn'
      Runtime: 'python3.9'
      Timeout: 60
      Environment:
        Variables:
          sns_arn: !Join
              - ':'
              - - 'arn:aws'
                - !Select [2, !Split [":", !Ref SNSNotificationTopic]]
                - !Sub ${AWS::Region}
                - !Select [4, !Split [":", !Ref SNSNotificationTopic]]
                - !Select [5, !Split [":", !Ref SNSNotificationTopic]]

  ForwardSnsNotificationGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ForwardSnsNotification}'
      RetentionInDays: !Ref LogsRetentionInDays

  ECLandingZoneSecLogLocalSNSTopicParameter:
    DependsOn:
      - LocalSNSNotificationTopic
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/org/member/Local_SecLog_sns_arn'
      Description: Contains the Local SNS Topic Arn for Landing Zone
      Type: String
      Value: !Ref LocalSNSNotificationTopic