AWSTemplateFormatVersion: 2010-09-09

#   --------------------------------------------------------
#   Version History
#
#   v1.0.0    J. Silva   Initial Version
#   --------------------------------------------------------

Description: >-
    Creates S3 bucket for LogShipper Lambda functions 

Resources:

    #   -------------------
    #   Code Repo Bucket
    #   -------------------

    LambdaArtefactsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName:
                Fn::Join:
                - ""
                - - "lambda-artefacts-"
                  - Ref: AWS::AccountId
            PublicAccessBlockConfiguration:
              BlockPublicAcls: true
              BlockPublicPolicy: true
              IgnorePublicAcls: true
              RestrictPublicBuckets: true
    
    LambdaArtefactBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket:
                Ref: LambdaArtefactsBucket
            PolicyDocument:
                Statement:
                 -
                   Sid: "CloudformationPermissions"
                   Effect: "Allow"
                   Action: "s3:*"
                   Principal:
                    Service:
                     - "cloudformation.amazonaws.com"
                   Resource: !GetAtt LambdaArtefactsBucket.Arn
                 

    
    LambdaArtefactBucketAccessRole:
        Type: 'AWS::IAM::Role'
        Properties:
          AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
              - 
                Effect: Allow
                Principal:
                    AWS:
                    - Fn::Join:
                      -  ""
                      - - "arn:aws:iam::"
                        - Ref: AWS::AccountId
                        - ":role/BrokerAccessLandingZoneNoMFARole"
                Action:
                - 'sts:AssumeRole'
          Policies:
            - PolicyName: root
              PolicyDocument:
                Version: 2012-10-17
                Statement:
                  - 
                    Effect: Allow
                    Action: 's3:*'
                    Resource: !GetAtt LambdaArtefactsBucket.Arn
